from .enums import Enum


class Language(Enum):
    english = "en"
    english_simplified = "en_US"

    arabic = "ar"
    assamese = "as"
    azerbaijani = "az"
    belarusian = "be"
    bulgarian = "bg"
    bengali = "bn"
    breton = "br"
    catalonian = "ca"
    cebuano = "ceb"
    central_kurdish = "ckb"
    czech = "cs"
    danish = "da"
    german = "de"
    greek = "el"
    spanish = "es"
    spanish_latin_america = "es_419"
    estonian = "et"
    finnish = "fi"
    filipino = "fil"
    french = "fr"
    irish = "ga"
    hindi = "hi"
    croatian = "hr"
    hungarian = "hu"
    armenian = "hy"
    indonesian = "id"
    icelandic = "is"
    italian = "it"
    japanese = "ja"
    korean = "ko"
    luxembourgish = "lb"
    lithuanian = "lt"
    macedonian = "mk"
    malay = "ms"
    norwegian_bokmal = "nb_NO"
    dutch = "nl"
    persian = "fa"
    polish = "pl"
    portuguese_brazil = "pt_BR"
    portuguese_portugal = "pt_PT"
    romanian = "ro"
    russian = "ru"
    slovak = "sk"
    slovenian = "sl"
    albanian = "sq"
    serbian = "sr"
    sinhalese = "si"
    swedish = "sv"
    tamil = "ta"
    thai = "th"
    turkish = "tr"
    ukranian = "uk"
    urdu = "ur"
    venetian = "vec"
    vietnamese = "vi"
    chinese_simplified = "zh_Hans"
    chinese_traditional = "zh_Hant"
    latvian = "lv"

    tokipona = "tokipona"
    esperanto = "esperanto"

    owo = "owo"
    pirate = "pr"
    bottom = "bottom"
    leet = "leet"
    piglatin = "piglatin"
    enchantment_table = "enchantment"


__all__ = ("Language",)
